version: '3.8'
services:
  app:
    build: .
    command: pnpm run start:dev
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5434/classmate?schema=public
    ports:
      - '8000:8000'
    depends_on:
      - db
    restart: always

    networks: -my-network

  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: classmate
    networks:
      - my-network

  test-db:
    image: postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: classmate
    networks: -my-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5050:80
    depends_on:
      - db
