FROM node:18-alpine


# Create app directory
WORKDIR /app

# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json yarn.lock ./
COPY prisma ./prisma/


# Install app dependencies
RUN apk --no-cache --virtual build-dependencies add  python3  make  g++
RUN yarn 
RUN apk del build-dependencies
RUN npm install -g node-gyp
RUN yarn add argon2


COPY . /app


EXPOSE 8000

CMD [ "yarn", "start:prod" ]


